[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
